### ISSUE TITLE
incompatabilities with potion timer

### ISSUE THREAD

**Issue by Heamaci** [Crendgrim/AutoHUD#1]
I just wanted to let you know that Bedrockify and Slight Gui Modifications disable the potion effect timer feature when together. Not a big deal, but you might want to look into it in the future. 

https://www.curseforge.com/minecraft/mc-mods/bedrockify
https://www.curseforge.com/minecraft/mc-mods/slight-gui-modifications

**Comment by Crendgrim** [comment]
Bedrockify overwrites the whole status effect area, I cannot fix that. You can circumvent it by disabling the "screenSafeArea" mixin, though.

Slight Gui Modifications doesn't seem to conflict with this mod at all, from what I could see.

**Comment by Heamaci** [comment]
> Bedrockify overwrites the whole status effect area, I cannot fix that. You can circumvent it by disabling the "screenSafeArea" mixin, though.
> 
> Slight Gui Modifications doesn't seem to conflict with this mod at all, from what I could see.

The bedrockify fix worked, thanks! It seems like the fluid potion feature is what isn't compatible in SGM.

**Comment by Crendgrim** [comment]
Ah: I remember seeing that pointed out in Status Effect Timers' repo as well. I'll add a note to the README, thanks :)
