### ISSUE TITLE
[Request]: Slot Cycler Compatibility for Minecraft 1.20.1?

### ISSUE THREAD

**Issue by Jouto55** [Crendgrim/AutoHUD#102]
Just one more thing on Issue https://github.com/Crendgrim/AutoHUD/issues/87 (Slot Cycler Compatibility)

Would it be possible to backport the Slot Cycler Compatibility to 1.20.1? So far it's only on Minecraft 1.20.3-1.20.4. 

I'd argue that a lot of the modding scene is still active around 1.20.1, given that many mods still haven't updated to 1.20.4 (L_Ender 's Cataclysm, The Aether, and Sculk Horde to name a few), and it's also the Minecraft version I still use for vanilla Minecraft and modded Minecraft.

If it is impossible to backport Slot Cycler compatibility due to technical reasons, I understand and will not inquire any more about Slot Cycler compatibility anymore.

**Comment by Crendgrim** [comment]
Yep, Fuzs would have to backport their compatibility to 1.20.1. Please add a comment to #87 if that ever happens and/or there's something else wrong with the compatibility layer.
