### ISSUE TITLE
Enhancement - Show XP Level when near an Enchanting Table

### ISSUE THREAD

**Issue by AzuryxxVortex** [Crendgrim/AutoHUD#106]
I assume it could be tricky, however could open up a lot of new possibilities.

Self explanatory, every time I have to enchant something I have to look it up, but if it was automatic- I'd be quite glad, truly
But well, quite tricky I assume

In any case, hope this finds you well-

=== Another Otherwordly Idea ===
It would certainly be interesting to see the whole mod config driven, where you can set anything and everything to hide and show when something happens. However that seems like a LOT of trouble, soo..

**Comment by Crendgrim** [comment]
Great idea! Added in 7.1 :)

> It would certainly be interesting to see the whole mod config driven, where you can set anything and everything to hide and show when something happens. However that seems like a LOT of trouble, soo..

It would indeed. However, even at its current state, the mod's config is getting way too big and I am trying to decide whether to cut down on options. Maintaining it is becoming an issue.
That being said, I laid the ground work for this in AutoHUD 7, with triggers being event-based now. This would enable me to ultimately go down this route. I will have to ponder that.

**Comment by AzuryxxVortex** [comment]
Thanks a ton, looking forward to the future!
Understandable concern for the config, too.
