### ISSUE TITLE
1.20.5 Fabric [Bug] Inventory and Settings auto-hide

### ISSUE THREAD

**Issue by Zorklis** [Crendgrim/AutoHUD#108]
Menu: https://youtu.be/ijg0hRS09MU
Settings: https://youtu.be/4SJToXyXbdE

**Comment by Zorklis** [comment]
I liked the inventory fade a bit

**Comment by Crendgrim** [comment]
I can replicate the inventory bug. I cannot replicate the video settings bug. What are your AutoHUD settings?

**Comment by Zorklis** [comment]
Both seem to be fixed on my end.
