### ISSUE TITLE
Auto HUD 1.6.1 crash on server join

### ISSUE THREAD

**Issue by mmmilord** [Crendgrim/AutoHUD#11]
1.6 worked fine, just downloaded the new ver and it crashed

[crash-2022-06-04_13.21.06-client.txt](https://github.com/Crendgrim/AutoHUD/files/8837679/crash-2022-06-04_13.21.06-client.txt)

**Comment by SyberiaKey** [comment]
Same.

[crash-2022-06-04_19.54.52-client.txt](https://github.com/Crendgrim/AutoHUD/files/8838074/crash-2022-06-04_19.54.52-client.txt)

**Comment by Crendgrim** [comment]
That was silly, should be fixed in 1.6.2, sorry about that!
