### ISSUE TITLE
HUD elements not triggering after changing dimension

### ISSUE THREAD

**Issue by ChazMeister** [Crendgrim/AutoHUD#112]
I'm using the latest version 7.1 on Fabric on Minecraft 1.20.6.

Upon opening a world AutoHUD functions correctly until I go through a Nether or End portal. Then health/hunger/armour/experience/air/hotbar(some cases) elements stop showing up/behaving correctly when they should be triggered.

Examples:
If the health/hunger bar is not showing when going through the portal, it'll then not show up when you take damage or get hungry.
If the health/hunger bar is showing when going through the portal, they'll get stuck showing and not go away when they should.

Tested in both single and multiplayer. Exiting and rejoining the world or server makes it work properly again.

This happens even with a fresh config file. Also disabled all other mods than just AutoHUD, Cloth Config and Fabric API to check and it still happens.

I used to use version 6.5 on Minecraft 1.20.4 and this doesn't happen on that, so seems to have been introduced since.

**Comment by Crendgrim** [comment]
Fixed, thanks the the report!
