### ISSUE TITLE
Fade-out on crosshair not working in 1.21

### ISSUE THREAD

**Issue by AstudilloMarillo** [Crendgrim/AutoHUD#115]
Think this is an AutoHUD thing, but it might be Dynamic Crosshair. In 1.21, the fade-out of the crosshair is not working, it just disappears after the specified "fade-out time". Also, when any value except 0.00 is selected on 'Fade-out limit', the crosshair will not disappear or fade at all.

**Comment by Crendgrim** [comment]
Thanks for the report, fixed with DynamicCrosshair 8.0.1
