### ISSUE TITLE
`autohud-7.2.3+1.21-neoforge` game crashes when launching

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Crendgrim/AutoHUD#116]
The game crashes on launch when Auto HUD and YACL are installed on a 1.21 NeoForge instance.

[_Crash log_](https://gist.github.com/3gf8jv4dv/cb7ce807c8f3e538f87c1bb1a9a2081c)

**Comment by Crendgrim** [comment]
Actually fixed now, apologies.
