### ISSUE TITLE
Auto HUD moves all UI down roughly 40%

### ISSUE THREAD

**Issue by TheGreyRaven** [Crendgrim/AutoHUD#121]
Hey!
This is not really a code related issue but more likely a mod incompatibility, I currently have the following mods in a private modpack that me and some friends uses.

<ul>
	<li>Botania</li>
	<li>McJtyLib</li>
	<li>ShetiPhianCore</li>
	<li>CTOV - Chef's delight Compat</li>
	<li>Just Enough Resources (JER)</li>
	<li>CC: Tweaked</li>
	<li>SuperMartijn642's Core Lib</li>
	<li>Industrial Foregoing: Souls</li>
	<li>YUNG's Better Jungle Temples</li>
	<li>Chimes</li>
	<li>Just Enough Professions (JEP)</li>
	<li>RFTools Control</li>
	<li>Double Doors</li>
	<li>More Axolotl Variants API</li>
	<li>Fusion (Connected Textures)</li>
	<li>Lionfish-API</li>
	<li>Sophisticated Core</li>
	<li>Just Enough Archaeology</li>
	<li>Waystones</li>
	<li>Additional Lanterns</li>
	<li>Create: Trimmed</li>
	<li>Bad Wither No Cookie - Reloaded</li>
	<li>Simply Light</li>
	<li>noisium-forge-2.0.3-mc1.20-1.20.1</li>
	<li>Macaw's Roofs</li>
	<li>EdivadLib</li>
	<li>Grass Overhaul</li>
	<li>Create: Diesel Generators</li>
	<li>Xaero's Minimap</li>
	<li>Cupboard</li>
	<li>Titanium</li>
	<li>Create: Quark Runes</li>
	<li>Fuel Goes Here</li>
	<li>L_Ender's Cataclysm</li>
	<li> Integrated Crafting</li>
	<li>CTOV - Friends and Foes Compat</li>
	<li>When Dungeons Arise: Seven Seas</li>
	<li>Additional Structures</li>
	<li>Architectury API (Fabric/Forge/NeoForge)</li>
	<li>pv-addon-sculk</li>
	<li>Corail Woodcutter</li>
	<li>Quark Oddities</li>
	<li>Immersive structures</li>
	<li>Athena</li>
	<li>Clumps</li>
	<li>Cristel Lib</li>
	<li>Small Ships</li>
	<li>Sophisticated Storage</li>
	<li>Corn Delight[Forge]</li>
	<li>TorchMaster</li>
	<li>Ducky Peripherals</li>
	<li>Mouse Tweaks</li>
	<li>immersive_aircraft-1.0.1-1.20.1-forge</li>
	<li>AI Improvements</li>
	<li>Thermal Expansion</li>
	<li>spark</li>
	<li>Mindful Darkness</li>
	<li>Energy Meter</li>
	<li>Powah!</li>
	<li>Supplementaries Squared</li>
	<li>Silent Lib</li>
	<li>Zeta</li>
	<li>Alex's Mobs</li>
	<li>Steam_Rails-1.6.4-forge-mc1.20.1</li>
	<li>Create Slice &amp; Dice</li>
	<li>CC:C Bridge</li>
	<li>Placebo</li>
	<li>Quark</li>
	<li>Chunky</li>
	<li>starlight-1.1.2-forge.1cda73c</li>
	<li>Cyclops Core</li>
	<li>Hidden Names</li>
	<li>Thermal Dynamics</li>
	<li>Iron Jetpacks</li>
	<li>Cucumber Library</li>
	<li>Handcrafted</li>
	<li>Macaw's Doors</li>
	<li>FTB Library (Forge)</li>
	<li>YUNG's API</li>
	<li>EnderChests</li>
	<li>Corail Tombstone</li>
	<li>Create Encased</li>
	<li>Construction Wand</li>
	<li>Oculus</li>
	<li>Create Enchantment Industry</li>
	<li>Lithostitched</li>
	<li>moremobvariants-forge-1.20.1-1.3.0.1</li>
	<li>Nether's Delight</li>
	<li>Balm (Forge Edition)</li>
	<li>radium-mc1.20.1-0.12.3-git.50c5c33</li>
	<li>Industrial Foregoing</li>
	<li>Macaw's Bridges</li>
	<li>Controlling</li>
	<li>Bookshelf</li>
	<li>Jumpy Boats</li>
	<li>Thermal Innovation</li>
	<li>More Music Discs</li>
	<li>pv-addon-soundphysics</li>
	<li>Better Advancements</li>
	<li>Macaw's Fences and Walls</li>
	<li>Searchables</li>
	<li>balm-forge-1.20.1-7.3.4-all</li>
	<li>Ensorcellation</li>
	<li>Incendium</li>
	<li>Refined Storage Addons</li>
	<li>Create: Connected</li>
	<li>TextruesDummyMod</li>
	<li>dynamiccrosshair-7.4.4-1.20-forge</li>
	<li>Twilight's Flavors &amp; Delight</li>
	<li>dynamic-fps-3.5.0-minecraft-1.20.0-forge</li>
	<li>Caupona</li>
	<li>Wavey Capes</li>
	<li>The Twilight Forest</li>
	<li>Mekanism Tools</li>
	<li>Nature's Compass</li>
	<li>CreateNumismatics-1.0.6-forge-mc1.20.1</li>
	<li>Create: Power Loader</li>
	<li>Fastload</li>
	<li>Ars Nouveau</li>
	<li>Refined Storage</li>
	<li>Delightful Sandwiches</li>
	<li>Connected Glass</li>
	<li>Embeddium/Rubidium Extras</li>
	<li>RFTools Base</li>
	<li>Additional Additions</li>
	<li>Angel Ring</li>
	<li>Absent by Design</li>
	<li>Saturn</li>
	<li>[Let's Do] Beachparty</li>
	<li>TrashSlot</li>
	<li>[Let's Do] NetherVinery</li>
	<li>Apotheosis</li>
	<li>BetterF3</li>
	<li>Beautify!</li>
	<li>Tectonic</li>
	<li>Exposure</li>
	<li>Joy of Painting</li>
	<li>Overflowing Bars</li>
	<li>Sophisticated Backpacks</li>
	<li>FerriteCore</li>
	<li>Farsight [Forge]</li>
	<li>immersive_armors-1.6.1-1.20.1-forge</li>
	<li>Enderman Overhaul</li>
	<li>Creeper Overhaul</li>
	<li>Kotlin for Forge</li>
	<li>ElevatorMod</li>
	<li>EpheroLib</li>
	<li>Delightful</li>
	<li>When Dungeons Arise</li>
	<li>Create Deco</li>
	<li>Snow Under Trees</li>
	<li>FLIB</li>
	<li>Friends&amp;Foes (Forge/NeoForge)</li>
	<li>Forbidden and Arcanus </li>
	<li>Patchouli</li>
	<li>Pehkui-3.8.2-1.20.1-forge</li>
	<li>Configured</li>
	<li>Crafting Recipes For Create</li>
	<li>Integrated Terminals</li>
	<li>Create Ore Excavation</li>
	<li>Cooking for Blockheads</li>
	<li>Create</li>
	<li>Silent's Gems</li>
	<li>EnderTanks</li>
	<li>polymorph-forge-0.49.5-1.20.1</li>
	<li>Macaw's Paintings</li>
	<li>[Let's Do] HerbalBrews</li>
	<li>Macaw's Trapdoors</li>
	<li>YUNG's Better Nether Fortresses</li>
	<li>Thermal: Extra</li>
	<li>Citadel</li>
	<li>Hearth &amp; Home</li>
	<li>CTOV - Farmer Delight Compat</li>
	<li>Better Archeology</li>
	<li>RFTools Storage</li>
	<li>Alex's Caves</li>
	<li>YUNG's Better End Island</li>
	<li>Macaw's Lights and Lamps</li>
	<li>More Axolotl Variants Mod</li>
	<li>Twigs</li>
	<li>Mekanism Generators</li>
	<li>End's Delight</li>
	<li>YUNG's Better Mineshafts</li>
	<li>Create: Extended Cogwheels</li>
	<li>Chef's Delight</li>
	<li>Ding</li>
	<li>[Let's Do] API</li>
	<li>AppleSkin</li>
	<li>Create: New Age</li>
	<li>Terralith</li>
	<li>Create: Liquid Fuel</li>
	<li>Twilight Forest: The Lost Blocks</li>
	<li>YUNG's Better Dungeons</li>
	<li>Dark Paintings</li>
	<li>Trash Cans</li>
	<li>Artifacts</li>
	<li>Just Enough Mekanism Multiblocks</li>
	<li>FastWorkbench</li>
	<li>Refined Storage: Requestify</li>
	<li>Collective</li>
	<li>Ender's Delight</li>
	<li>Create: Oppenheimered</li>
	<li>Chipped</li>
	<li>Explorer's Compass</li>
	<li>[Let's Do] Bakery</li>
	<li>Little Contraptions</li>
	<li>Raised</li>
	<li>Rechiseled</li>
	<li>Thermal Foundation</li>
	<li>ImmediatelyFast-Forge-1.2.18-1.20.4</li>
	<li>Macaw's Furniture</li>
	<li>Croptopia</li>
	<li>[Let's Do] Brewery</li>
	<li>Model Gap Fix</li>
	<li>AttributeFix</li>
	<li>Xaero's World Map</li>
	<li>curios-forge-5.9.1-1.20.1</li>
	<li>Aquaculture 2</li>
	<li>FallingTree</li>
	<li>immersive_paintings-0.6.7-1.20.1-forge</li>
	<li>Ad-Astra: Giselle Addon</li>
	<li>FastFurnace</li>
	<li>Botarium</li>
	<li>comforts-forge-6.3.5-1.20.1</li>
	<li>End Remastered</li>
	<li>BadOptimizations</li>
	<li>Lootr</li>
	<li>Distant Horizons</li>
	<li>Tom's Peripherals</li>
	<li>[Let's Do] Candlelight</li>
	<li>Xaero's Minimap &amp; World Map - Waystones Compatibility</li>
	<li>Create Central Kitchen</li>
	<li>Farming for Blockheads</li>
	<li>Towns-and-Towers-1.12-Fabric-Forge</li>
	<li>Jade Addons (Forge)</li>
	<li>Ice and Fire</li>
	<li>CoFH Core</li>
	<li>Integrated Dynamics</li>
	<li>Sound Physics Remastered</li>
	<li>YUNG's Better Ocean Monuments</li>
	<li>pv-addon-groups</li>
	<li>Jade 🔍</li>
	<li>FTB Ultimine (Forge)</li>
	<li>Advancement Plaques</li>
	<li>SebastrnLib</li>
	<li>Ad Astra</li>
	<li>SuperMartijn642's Config Lib</li>
	<li>Deeper and Darker</li>
	<li>Create: Copycats+</li>
	<li>Botany Trees</li>
	<li>Apothic Attributes (AttributesLib)</li>
	<li>Mekanism</li>
	<li>Dark Utilities</li>
	<li>Cloth Config API</li>
	<li>Auto HUD</li>
	<li>Resourceful Config</li>
	<li>Domum Ornamentum</li>
	<li>memoryleakfix-forge-1.17--1.1.5</li>
	<li>interiors-0.5.3-forge-mc1.20.1</li>
	<li>Supplementaries</li>
	<li>Ars Creo</li>
	<li>Create: Bells &amp; Whistles</li>
	<li>Create: Design n' Decor</li>
	<li>Silent's Delight</li>
	<li>Mysterious Mountain Lib</li>
	<li>Ocean's Delight</li>
	<li>Thermal Integration</li>
	<li>Mekanism Additions</li>
	<li>Cosmetic Armor Reworked</li>
	<li>Silent Gear</li>
	<li>Botany Pots</li>
	<li>Integrated Tunnels</li>
	<li>Extra Disks</li>
	<li>Farmer's Delight</li>
	<li>Better Third Person</li>
	<li>immersive_melodies-0.2.0-1.20.1-forge</li>
	<li>Advanced Peripherals</li>
	<li>Cataclysm Apotheosis Addon</li>
	<li>RFTools Dimensions</li>
	<li>Pig Pen Cipher</li>
	<li>Resourceful Lib</li>
	<li>Macaw's Windows</li>
	<li>[Let's Do] Vinery</li>
	<li>Common Capabilities</li>
	<li>Amendments</li>
	<li>Croptopia Delight</li>
	<li>Create: Misc and Things</li>
	<li>fast-ip-ping</li>
	<li>Naturalist</li>
	<li>Harvest with ease</li>
	<li>Delightful Burgers</li>
	<li>Fast Paintings</li>
	<li>ExtraStorage</li>
	<li>YUNG's Better Desert Temples</li>
	<li>Fast Leaf Decay</li>
	<li>embeddium-0.3.21-mc1.20.1</li>
	<li>Applied Energistics 2</li>
	<li>Refined Polymorphism</li>
	<li>GeckoLib</li>
	<li>Cataclysm Weaponery</li>
	<li>Crafting on a stick</li>
	<li>ChoiceTheorem's Overhauled Village</li>
	<li>FramedBlocks</li>
	<li>Iceberg</li>
	<li>Runelic</li>
	<li>RFTools Utility</li>
	<li>MrCrayfish's Furniture Mod</li>
	<li>Plasmo Voice</li>
	<li>modernfix-forge-5.18.1-mc1.20.1</li>
	<li>Mekanism: Ad Astra Ores</li>
	<li>Create: The Factory Must Grow</li>
	<li>Baubley Heart Canisters</li>
	<li>Additional Lights</li>
	<li>Apothic Curios</li>
	<li>Just Enough Items</li>
	<li>RFTools Power</li>
	<li>RFTools Builder</li>
	<li>Embeddium/Rubidium Dynamic Lights</li>
	<li>FastSuite</li>
	<li>YUNG's Better Strongholds</li>
	<li>Vegan Delight</li>
	<li>YUNG's Better Witch Huts</li>
	<li>Create: Dreams &amp; Desires</li>
	<li>Refined Cooking</li>
	<li>Rechiseled: Chipped</li>
	<li>Macaw's Paths and Pavings</li>
	<li>Packet Fixer</li>
	<li>Moonlight Lib</li>
	<li>Little Logistics</li>
	<li>Puzzles Lib</li>
	<li>Thermal Cultivation</li>
	<li>Valhelsia Core</li>
</ul>

The issue is when I add Auto HUD it moves all UI down roughly 40% (including the pause menu) and when the hotbar gets visible it moves everything up and then it looks normal until the hotbar gets hidden again.

![image](https://cdn.discordapp.com/attachments/380885083965620225/1256527952313712722/image.png?ex=66811858&is=667fc6d8&hm=457bab7071e01197870bd42353ffcd86da25b78291336f6d966fe4131c57a554&)

My guess would be that there is a mod installed that messes with the game rendering thus causing this issue, I have tried to remove mods one by one but the issue still persists, if someone have experienced the same issue and could have a suggestion on which mod is causing the issue it would be greatly appriciated.

I also do have some Java knowledge and would love to help out and add mod compatability!

Thanks for a really nice mod!

**Comment by Crendgrim** [comment]
The fastest way to figure out which mod it is is to remove about half of the mods and then see if the issue persists. If it does, remove another half; if it doesn't, add only the removed half back in. It's a bit more complicated due to libraries and dependencies but still a fairly quick process to figure out
