### ISSUE TITLE
[Bug] Incompatibility with Raised 4.0.0 (latest) - 1.21 & 1.20.4, Fabric

### ISSUE THREAD

**Issue by meowinqq** [Crendgrim/AutoHUD#125]
It appears that the most recent release of Raised (4.0.0) has changed a significant amount of systems under the hood, breaking the compatibility patches built into Autohud. Attempting to load the game with both mods leads to a crash, with Fabric pointing to the "RaisedCompat" function as the culprit. This same result has been observed in versions 1.20.4 and 1.21, though I've not tested any others.

 I know this is an incredibly new issue considering this iteration of Raised was released publicly just yesterday -- I was unsure of whether or not you were already aware of the changes, so I'd figured I'd make a report just in case..!

Thank you for all of the time and effort you've put into this mod, it really is nothing short of a gamechanger!

**Comment by Crendgrim** [comment]
I was not aware, thank you for bringing this to my attention!

**Comment by Crendgrim** [comment]
Hm, Raised changed substantially. It would require a lot of work to make it compatible. I can easily make it stop crashing, but it won't work properly. For now, consider Raised 4 to be incompatible with AutoHUD until I can find time to change things.
