### ISSUE TITLE
Game crashes when openining config

### ISSUE THREAD

**Issue by kadincool** [Crendgrim/AutoHUD#130]
Minecraft 1.20.1
Forge 47.3.0
Mods:
* Auto HUD - 6.3.6+1.20.1
* YetAnotherConfigLib - 3.5.0+1.20.1-forge
Steps to reproduce:
1. launch with above mods
2. navigate to mods > "Auto HUD" > Config
3. game crashes with exit code -1
[crash-2024-09-18_22.15.32-client.txt](https://github.com/user-attachments/files/17053423/crash-2024-09-18_22.15.32-client.txt)

**Comment by Crendgrim** [comment]
Yet another example of isXander/YetAnotherConfigLib#182, sadly

**Comment by kadincool** [comment]
oh, is there a version of YACL that doesn't have this problem?
