### ISSUE TITLE
crash 1.21.1 neo

### ISSUE THREAD

**Issue by Jupitor87** [Crendgrim/AutoHUD#133]
https://mclo.gs/5CmSBDC
neo 1.21.1
neoforge 21.1.61

**Comment by BugmanBugman** [comment]
https://gist.github.com/BugmanBugman/7ab823c8ea274770adc8ed016006e641

getting a crash on this too on startup

**Comment by Crendgrim** [comment]
When does this happen? On startup, before even loading into a world? I cannot reproduce it and I'm very confused how the mod can ever get into this state.

**Comment by Jupitor87** [comment]
Yes starts "loading mods" than just quits not like this matters but also happens with another one of your mods "dynamic crosshair"

**Comment by Crendgrim** [comment]
> Yes starts "loading mods" than just quits not like this matters but also happens with another one of your mods "dynamic crosshair"

Oh no, that does matter! Interesting.


> Edit: Seem to be a conflict with the mod Placebo "https://www.curseforge.com/minecraft/mc-mods/placebo" here is crash with just 2 mods installed [crash-2024-09-30_16.35.18-client.txt](https://github.com/user-attachments/files/17196675/crash-2024-09-30_16.35.18-client.txt)

Thank you for finding the actual incompatibility! Now I can figure out what Placebo does that could possibly cause this.
