### ISSUE TITLE
[Bug] No ranged weapons crosshair

### ISSUE THREAD

**Issue by nimbXnumb** [Crendgrim/AutoHUD#137]
Crosshair disappears when holding bow and crossbow. Swords (and other tools) always have it. By the way I'm using Dynamic Crosshair, but anyway it's a problem... Ranged weapon crosshair should always be visible for targeting.

**Comment by Crendgrim** [comment]
Thank you for the report! This is a bug in DynamicCrosshair, I have identified the issue and will publish a fix soon.

**Comment by Crendgrim** [comment]
Should be fixed with DynamicCrosshair 9.3
