### ISSUE TITLE
Revealing and hiding all components hides components that should  remain on the screen

### ISSUE THREAD

**Issue by luni3359** [Crendgrim/AutoHUD#14]
For example, if you have health and hunger set to display only when not full and they're not full, but you press R, then other components will show up on the screen but then after the visibleTime expires health and hunger will go away along with the components that have to exit.

This makes it so that health and hunger remain hidden indefinitely until the player becomes damaged, and I assume that the same happens when the hunger value changes too.

**Comment by Crendgrim** [comment]
Thanks for the report! Should be fixed with 1.7.2.
