### ISSUE TITLE
DetailArmorBar Not beeing hidden

### ISSUE THREAD

**Issue by obp3ter** [Crendgrim/AutoHUD#15]
It might just be me, but with [DetailArmorBar](https://modrinth.com/mod/detail-armor-bar) the armour is not hidden. Am I doing something wrong?

**Comment by Crendgrim** [comment]
If you are on Minecraft 1.19, are you using AutoHud 1.7.2?

It should work on Minecraft 1.18. On Minecraft 1.19, I attempted to re-add compatibility with version 1.7.2 (released a couple hours ago). Did that not work?

**Comment by obp3ter** [comment]
It's 1.19, I didn't see 1.7.2. With that one it did work.
