### ISSUE TITLE
Settings won't be saved - 1.19 (Fabric)

### ISSUE THREAD

**Issue by v1-valux** [Crendgrim/AutoHUD#18]
When I change any settings (Conditions on when to show Hunger Bar, Health Bar) and restart the game, the settings are restored to default.
Also I do not find any config-/ json file to make the changes persistent.

What can I do to fix this?

**Comment by Crendgrim** [comment]
That is odd behaviour that I cannot replicate. Running the mod should create a file `config/autohud.json5`.

What version of clothconfig are you using (I tested with 7.0.72 & 7.0.73)? Is your config folder writable/do other mods keep their settings?

**Comment by v1-valux** [comment]
Thanks for the quick reply.

I use cloth-config-7.0.72 and cloth-api-4.0.65.
other mods save settings as normal (at least what I tested until now).
the config-file is not there which might be the problem..
Permissions are correct (rwx) (I'm on Linux)

**Comment by v1-valux** [comment]
I found out what causes the issue.
I used to have the /config directory symlinked from a central folder (for subversions eg. 1.18 / 1.18.2)
but somehow some mods cannot write into that symlink, where others can.

Just to let you know, maybe it is fixable (to write into symlinks aswell).

But as for this issue, it can be closed. :)

**Comment by Crendgrim** [comment]
Oh, interesting. I'm using clothconfig's AutoConfig for both mods, so I assume that all mods using that would have the same problem (but I don't know which do!)... maybe I'll work on migrating away from autoconfig. Thank you for the information, and I'm glad you solved your problem!
