### ISSUE TITLE
BerdinskiyBear Armor HUD does not hide

### ISSUE THREAD

**Issue by vos6434** [Crendgrim/AutoHUD#2]
The HUD doesn't hide but the items do.

https://user-images.githubusercontent.com/21976486/168706730-1b5d2d83-bb0e-4c61-bfd3-8f9a4acdb3ed.mp4

**Comment by Crendgrim** [comment]
Fixed in def15d4f33c4b9f5a49db7c2a9226d4ff0cf1750, at least for hotbar-aligned (default) setup.

**Comment by vos6434** [comment]
Warning indicators don't move.

https://user-images.githubusercontent.com/21976486/169101831-6e2a312d-9589-47a8-a2cb-d43a3a2e9aa7.mp4

**Comment by Crendgrim** [comment]
I sadly can't change the height, that would require changes in the other mod. I have to consider this "good enough" for now.
