### ISSUE TITLE
Problems with EssentialGUI

### ISSUE THREAD

**Issue by dlfnn** [Crendgrim/AutoHUD#20]
If animation is set to move, when hud automatically hides, every GUIs including which from EssentialGUI and vanilla are moved down a certain distance visually, while the actual position where you can click them remains the same.
![image](https://user-images.githubusercontent.com/94152497/192146964-a56bee35-f5f6-4fe3-88cc-6bb4d93088c5.png)
https://www.curseforge.com/minecraft/mc-mods/essentialgui

**Comment by dlfnn** [comment]
Wait this mod is not opensource... should I stop using it then

**Comment by Crendgrim** [comment]
EssentialGUI changes a lot about the UI, and since (as you noticed) it's not open source, I have not looked into adding compatibility at all yet.

**Comment by Crendgrim** [comment]
While I think EssentialGUI is antithetical to AutoHUD, I have fixed the whole UI being shifted in AutoHUD 2.2.

I have only tested the standard, basic configuration of EssentialGUI. Feel free to reopen if there's problems with specific setting combinations of either mods.
