### ISSUE TITLE
Pause menu shifted down when running in Move mode

### ISSUE THREAD

**Issue by Derpford** [Crendgrim/AutoHUD#21]
When AutoHUD is set to move the hud down instead of fade it, it also moves the pause menu down.

I have Sodium and Indium installed, as well as OneBar (which changes the hotbar HUD) and Create (which adds a button to the pause menu and also does some stuff to the hotbar). Full mod list can be posted on request.

**Comment by Crendgrim** [comment]
Thank you for the report!

This bug can occur if another mod also changes the hotbar, and overrides the "move back" hook of AutoHUD. I am strongly assuming it's an incompatibility between OneBar and AutoHUD; will investigate later.

**Comment by Crendgrim** [comment]
I have fixed this in AutoHUD 2.2.

Running both mods together will reveal OneBar whenever any of (health, armor, air, hunger) are set to change. You may use AutoHUD's options to configure their respective vanilla components. The OneBar handler inherits from those and should automatically reveal the OneBar whenever you wish.
Also OneBar's special experience bar renderer is working correctly.

Only caveat: OneBar appears to have a lot of other options that I did not delve into. Please do let me know if there are any other triggers that you wish would automatically reveal the OneBar again.

**Comment by Crendgrim** [comment]
Apologies; I don't mind fixing compatibility issues, but I also definitely do not have the time to search through 340 mods for you. Especially based on "one of these mods may cause some otherwise unspecified weird things".

**Comment by Derpford** [comment]
Understandable, I don't either :P

Thanks anyway.

**Comment by Crendgrim** [comment]
Hi, I have found a way to implement my mixins more defensively by making use of another black magic project. This should theoretically make sure this kind of bug can never happen again, unless a mod does something very bad. I've published this as version 2.3 (pending on CurseForge). Please do test again if this happens to also resolve the remaining graphical glitches you've encountered. :)
