### ISSUE TITLE
[Suggestion] Have HUD "fade out" in the style of legacy console versions

### ISSUE THREAD

**Issue by nitrogenfive** [Crendgrim/AutoHUD#22]
It's hard to find an example due to the nature of the suggestion, but basically when the HUD goes unused for a while (no change in, for example, item held) the HUD would fade out to about 20% opacity. It would still be visible, just less obvious.

**Comment by Crendgrim** [comment]
I like this idea! I pushed AutoHUD 2.3 which adds an option to set a maximum fade limit. If you set that to 0.2 and play around with the reveal type and time revealed settings, I hope you can achieve the desired effect!
If there's something missing or this does not work as you expected, feel free to reopen this issue :)
