### ISSUE TITLE
Items in hotbar not showing what block it is

### ISSUE THREAD

**Issue by QQuirkyy** [Crendgrim/AutoHUD#23]
![Screenshot 2022-10-16 141752](https://user-images.githubusercontent.com/115911875/196017721-706fe17b-f4d1-4be6-832b-40255563d81a.png)

**Comment by Crendgrim** [comment]
Are you on "fade" or "move" animation mode? What version of AutoHUD is this, and do you use anything like Sodium or OptiFabric?

**Comment by QQuirkyy** [comment]
Its V2.2.1+1.19.1 and im using move aswel as Lithium

**Comment by QQuirkyy** [comment]
I swapped to a normal version of mc then when i launched the fabric version again i am able to see blocks again and im not sure what would of caused the bug

**Comment by Crendgrim** [comment]
Hm, quite odd. I have not seen that yet. Had you temporarily switched to "fade" mode when the bug occurred?
If it does happen again, please do let me know.

**Comment by QQuirkyy** [comment]
I havent messed with any settings i didnt even know a fade setting existed till you told me but i guess to fix it you just got to launch a diffrent thing then launch fabric again
