### ISSUE TITLE
Crashes due to duplicate MixinExtrasBootstrap class definition

### ISSUE THREAD

**Issue by N-Ved** [Crendgrim/AutoHUD#24]
https://hastebin.com/mecetujeca.sql

I get this error when trying to use the mod on curseforge. I'm using Fabric.

**Comment by Crendgrim** [comment]
I am unable to reproduce this bug. Can you give me more information about your installation?

What version of Minecraft are you on, and what is your full mod list?

**Comment by N-Ved** [comment]
Hi, I am using Minecraft 1.19.2, Fabric version 0.14.10 and this is my [mod list](https://hastebin.com/yoqogivuve.css), this it the [full log](https://hastebin.com/uzuvivegeg.yaml) and I am using the curseforge launcher. Please do ask if you need anything else.

**Comment by N-Ved** [comment]
> I am unable to reproduce this bug. Can you give me more information about your installation?
> 
> What version of Minecraft are you on, and what is your full mod list?

Hi, I am using Minecraft 1.19.2, Fabric version 0.14.10, Auto HUD version 2.3.1 and this is my [mod list](https://hastebin.com/yoqogivuve.css), this it the [full log](https://hastebin.com/uzuvivegeg.yaml) and I am using the curseforge launcher. Please do ask if you need anything else.

**Comment by Crendgrim** [comment]
This must be some incompatibility between AutoHUD and some other mod in your list (potentially both including MixinExtras?), considering it does not happen on its own or in my installations. I have one blind guess what could fix it, and have pushed a beta version to modrinth: https://modrinth.com/mod/autohud/version/2.3.2%2B1.19.1

Could you test that and see if it changes the behaviour?

As an alternative, could you post the same mod list when AutoHUD is not installed, and see if it still mentions MixinExtras somewhere?

**Comment by Crendgrim** [comment]
Nevermind for the beta version. This appears to be a problem with MixinExtras when it is being initialised differently by two mods. For the time being, you should be able to downgrade to AutoHUD 2.2.1. That version did not use MixinExtras yet, so it should be unaffected.

**Comment by Crendgrim** [comment]
Ah, I believe I found it.

Your mod list has Debugify 2.7.1. Looking at the patch notes for Debugify 2.8.0, it seems like updating that mod will fix the crashes: https://modrinth.com/mod/debugify/version/2.8.0

Can you try that and let me know if it works?

**Comment by N-Ved** [comment]
That fixed it! Thanks! But I have another question... By any chance could you make the HUD items not visible after the anim? to prevent this? 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/87060868/199672061-14846040-6881-4cb8-9547-74700f7ea41a.png">

**Comment by Crendgrim** [comment]
Oh wow, what in the world is that? Why do you have so many hearts??

Would you mind opening a new issue for that? I foresee that not being trivial, since stacked bars (in this case, the armour bar) will be tricky to get right.
For now, you can manually tweak the distance that components move out by in the settings.
