### ISSUE TITLE
Fade mode compatibility issue

### ISSUE THREAD

**Issue by firig43** [Crendgrim/AutoHUD#26]
- Game version **1.19.2**
- AutoHUD verison **2.3.1+1.19.1**
- Sodium verison **0.4.4+build.18**

When fade mode is used alongside Sodium, hotbar icons will disappear completely instead(icons suddenly snap out after the hotbar completely fade out).
![2022-11-08_19 50 57](https://user-images.githubusercontent.com/94965905/200556992-8f3180c8-0eb5-4d4f-9075-81e31a55549d.png)

**Comment by Crendgrim** [comment]
This is listed in the mod description as a known issue, but it's good to have this to track it. For if I ever find a way to fix it. I couldn't figure it out in the past even after spending quite a few hours on it.

**Comment by Shad0wolf0** [comment]
This seems to be fixed in the latest Sodium update 0.4.9

**Comment by Crendgrim** [comment]
Finally fixed it in version 3.0!
