### ISSUE TITLE
I set armor hud doesn't show

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Crendgrim/AutoHUD#27]
I said armor HUD to be said to always but it's not showing

**Comment by Crendgrim** [comment]
I cannot replicate this bug either. What armour are you wearing? Note that the armour bar doesn't show if you have no armour on, just like in vanilla.

**Comment by Aces-and-Jacks** [comment]
I think it's caused by https://modrinth.com/mod/detail-armor-bar

**Comment by Crendgrim** [comment]
Should be fixed in 2.5. That version also includes the workaround for #28.
