### ISSUE TITLE
Hotbar icon stack numbers not disappearing with Immediately Fast

### ISSUE THREAD

**Issue by rght925h** [Crendgrim/AutoHUD#31]
~~Numbers for item stacks in the hotbar are not disappearing it seems.
Reference here:
https://imgur.com/a/dMZdrYK~~

Thank you for this great mod! :-)

**Edit:** _Sorry, my bad. After further testing, this seems to be an incompatibility with "[Immediately Fast](https://modrinth.com/mod/immediatelyfast/changelog)"!_

**Comment by bluebear94** [comment]
I am getting reports of similar behavior with [Caxton](https://gitlab.com/Kyarei/caxton/-/issues/8).

**Comment by Crendgrim** [comment]
As of ImmediatelyFast 1.1.8, it appears to work fine in both move and fade mode, as they have disabled item batching by default.

See RaphiMC/ImmediatelyFast#16 for reference.
