### ISSUE TITLE
Doesn't seem to respect OneBar's "Hotbar item tooltip down" option

### ISSUE THREAD

**Issue by Madis0** [Crendgrim/AutoHUD#34]
AutoHUD always seems to use the vanilla height for the hotbar tooltip, regardless of whether that option is enabled.

https://github.com/Madis0/OneBar/blob/main/src/main/java/io/github/madis0/mixin/InGameHudMixin.java#L78

**Comment by Crendgrim** [comment]
I cannot reproduce this anymore with the latest AutoHUD and OneBar. Either it magically got fixed by me cleaning up, or you did something in the meantime. Hurray for it working fine now, though ;)
