### ISSUE TITLE
Crash on 1.19.3

### ISSUE THREAD

**Issue by Zetsphiron** [Crendgrim/AutoHUD#35]
Using the Fabric loader, Fabric API and Cloth Config.

[crash-2023-01-21_15.47.56-client.txt](https://github.com/Crendgrim/AutoHUD/files/10473242/crash-2023-01-21_15.47.56-client.txt)

**Comment by Crendgrim** [comment]
I keep forgetting to double check fade mode compatibility; apologies. Uploaded version 2.5.2 that fixes the crash.
