### ISSUE TITLE
1.19.3 Detail Armor Bar not hidden with fade

### ISSUE THREAD

**Issue by Shad0wolf0** [Crendgrim/AutoHUD#36]
Hi! I'm on 1.19.3 with Auto HUD (2.5.2) using the fade mode. The Detail Armor Bar (2.6.3) mod doesn't seem to fade and hide.

**Comment by Crendgrim** [comment]
This has prompted me to finally rewrite the ugly, hacky fade mode implementation I had. With the new and clean one, Detail Armor Bar just works again!

Released as 3.0 :)

**Comment by Shad0wolf0** [comment]
Okay! I tested 3.0 and 3.1 and the detailed armor bar still doesn't fade away

**Comment by Crendgrim** [comment]
This is weird, I am 100% sure it was working in my dev environment, but I can confirm that it doesn't work. Huh. Apologies, will have to check that tomorrow.

**Comment by Crendgrim** [comment]
This is very confusing. It works perfectly fine when in my dev environment, and perfectly not when outside.. this might take a while to figure out

**Comment by Crendgrim** [comment]
Figured it out! Remapping is weird. Fixed in 3.2

**Comment by Crendgrim** [comment]
Pushed it for 1.19.2 :)
