### ISSUE TITLE
Separate animation speeds

### ISSUE THREAD

**Issue by Madis0** [Crendgrim/AutoHUD#37]
IMO the HUD should appear twice as fast and disappear twice as slow. For that, the mod needs two animation speed options :stuck_out_tongue:

**Comment by Crendgrim** [comment]
Funnily enough, I considered adding a separate animation speed for the different animation modes. But that would make 4 speeds already, then. Hmm.

**Comment by Crendgrim** [comment]
I am speed. Check out version 3.1 :)
