### ISSUE TITLE
3.0+1.19.3 Hiding is broken

### ISSUE THREAD

**Issue by Zorklis** [Crendgrim/AutoHUD#38]
![2023-02-15_20 00 50](https://user-images.githubusercontent.com/85455465/219114319-136f0648-05fa-4637-b956-b436c152d0c6.png)

**Comment by Crendgrim** [comment]
Please provide more information. What mod is the item list, what other mods do you have installed?

**Comment by Zorklis** [comment]
> Please provide more information. What mod is the item list, what other mods do you have installed?

I don't see how that helps if 2.5.2+1.19.3 worked perfectly

**Comment by Crendgrim** [comment]
.. so that I can reproduce the issue and fix it?

It doesn't show these issues in an otherwise vanilla installation.

**Comment by Zorklis** [comment]
![image](https://user-images.githubusercontent.com/85455465/219116148-168bc093-53e7-4323-9ba7-5f24f6b1c707.png)
My mod list

**Comment by Crendgrim** [comment]
Thank you. With that, I was able to replicate and figure out the bug, it stems from the newly introduced ability to enable fade and move mode at the same time, but only when AppleSkin is installed.

Just pushed version 3.1 that fixes this issue.
