### ISSUE TITLE
Fade hotbar but show items like before v3.0

### ISSUE THREAD

**Issue by Shad0wolf0** [Crendgrim/AutoHUD#39]
I don't know if it was intentional or not, but before version 3.0 when the hotbar would fade, the items still showed up without the number of items. I actually liked that effect because it seemed newbie friendly. Wondering if its possible to bring that back?

**Comment by Crendgrim** [comment]
That "feature" was a bug if you ran Auto HUD together with Sodium _some of the time_, so it was not intentional. This is the first time I've heard of someone actually wanting it. I will consider adding it as a proper feature.

**Comment by Shad0wolf0** [comment]
Thank you for your consideration! There are transparent hotbar texture packs, but I still want a custom hotbar texture

**Comment by Crendgrim** [comment]
Would you want the items to stay at full visibility or get slightly translucent? Personally I'm leaning towards the second option.

**Comment by Shad0wolf0** [comment]
Definitely slightly translucent, so it can be a little more immersive

**Comment by Crendgrim** [comment]
I added it in version 3.2. :)

Go to Component settings, under Hotbar the latest entry ("Fade-out limit for hotbar items") can be set to something like 0.3 or 0.4 to achieve the effect.

It will also draw the stack counts now.
