### ISSUE TITLE
3.0 1.19.2 Appleskin Compatibility

### ISSUE THREAD

**Issue by greensad** [Crendgrim/AutoHUD#40]
Could we get the 1.19.3 fix added in 3.1 backported to 1.19.2 by chance? I'm experiencing the same issue discussed here: https://github.com/Crendgrim/AutoHUD/issues/38

**Comment by Crendgrim** [comment]
Uh.. AutoHUD 3.1 for 1.19-1.19.2 is already released through both CurseForge and Modrinth. :confused:

**Comment by Crendgrim** [comment]
Oh, I see, only through CurseForge. Somehow I forgot to push 3.1 to Modrinth... oops.

**Comment by greensad** [comment]
thanks!
