### ISSUE TITLE
Advanced Component Settings won't save between sessions on CurseForge

### ISSUE THREAD

**Issue by RadLaddy** [Crendgrim/AutoHUD#42]
Hello

First of all love this mod!

I've got an issue where the config settings are resetting to default every time I launch the game. I saw there was a previous issue raised similar to this, but the confusing part about it is it's only the advanced components that get reset, everything else remains the same.

I like to have very specific animations so it's a bit of a headache re-inputting them every time lol. I have tried multiple different config menus and typed the json5 manually before launching but nothing's worked. It only writes over the advanced settings and leaves the rest. Tried older versions and amended the config files to match how they're laid out but it was still happening.

I'm running a modpack on CurseForge if it's got anything to do with the file directory

Hope you can help!

[autohud.json5 (.txt version).txt](https://github.com/Crendgrim/AutoHUD/files/10960417/autohud.json5.txt.version.txt)

**Comment by Crendgrim** [comment]
Oh, that is a very interesting interaction. Apologies for the complications. I pushed a version that should fix this (3.2.1). Thank you the clear report, and let me know if it breaks again!

**Comment by RadLaddy** [comment]
Brilliant, thankyou I’ll give it a go tonight! 🙂
