### ISSUE TITLE
Compatibility Issue With Ugly Scoreboard Fix Mod

### ISSUE THREAD

**Issue by Talbe1** [Crendgrim/AutoHUD#43]
When AutoHUD is present with the Ugly Scoreboard Fix mod, the background of the scoreboard turns completely black.
The following image shows what I set the scoreboard to look like.
![2023-03-14_21 55 48](https://user-images.githubusercontent.com/104154497/225123028-beebabfc-2822-4e87-ba6a-49ea671965dc.jpg)

And this is what the scoreboard looks like after installing the AutoHUD mod (disabling AutoHUD didn't solve the issue).
![2023-03-14_21 58 20](https://user-images.githubusercontent.com/104154497/225123205-74b751e9-c22c-4b3c-b6e5-f4996d670b97.jpg)

Is there an easy fix for this compatibility issue? Because I want the scoreboard to look the way I want it to.

**Comment by IdkWhatToCallMe123** [comment]
Maybe you already solved it by now, but I think something else is causing your issue, since I can use both mods perfectly fine.

**Comment by Talbe1** [comment]
I haven't had solved it yet. It could be that I missed somwthing what I was trying to find the cause. I will dig further into this problem today.

**Comment by Talbe1** [comment]
I looked further into the issue and it still persists for me when launching the game with just the following mods:
![image](https://user-images.githubusercontent.com/104154497/230705432-cc112dbb-2678-4403-9d0a-02439dfc4624.png)


@IdkWhatToCallMe123, what version of the mod**s** and game were you using that doesn't have this issue?
My issue occurs on my 1.18.2 Fabric client.

**Comment by IdkWhatToCallMe123** [comment]
@Talbe1 I'm using Uglyscoreboardfix 2.7, AutoHUD v3.2.1 and MC version 1.19.2

**Comment by Sotumney** [comment]
@Talbe1 If you're still encountering this issue, set your title and background color in UglyScoreboardFix to #0a00000a. This only leaves a slight background, but almost invisible.
