### ISSUE TITLE
Advanced Component Settings Reset Upon Relaunching the Game

### ISSUE THREAD

**Issue by Talbe1** [Crendgrim/AutoHUD#45]
This issue has to do with mod version 2.1 which was made for Minecraft 1.18.2.
It is exactly the same as issue #42.

I like this mod A LOT, it's **absolutely fantastic**, apart from this single bug.
I do not know if you wish to support versions of the mod made
for previous versions of the game. But if you do, please fix this issue,
it is quite annoying.

**Comment by Crendgrim** [comment]
Sure, if 1.18.2 still has users, I can certainly backport that fix.

**Comment by Talbe1** [comment]
Thank you very much!
