### ISSUE TITLE
ModMenu throwing error for configuration button with FeatherClient

### ISSUE THREAD

**Issue by temginson** [Crendgrim/AutoHUD#46]
![image](https://user-images.githubusercontent.com/132342905/235622319-eb806c1e-dc97-49a0-852d-ac7080478cda.png)

**Comment by Crendgrim** [comment]
I have never seen this before. What versions of Fabric, Fabric API, Cloth Config and Mod Menu are you using?

**Comment by temginson** [comment]
How do i see that?

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

Från: ***@***.***>
Skickat: 02 May 2023 11:17
Till: ***@***.***>
Kopia: ***@***.***>; ***@***.***>
Ämne: Re: [Crendgrim/AutoHUD] ModMenu throwing error for configuration button (Issue #46)


I have never seen this before. What versions of Fabric, Fabric API, Cloth Config and Mod Menu are you using?

**Comment by Crendgrim** [comment]
There's multiple ways. For one, it should show all the mods' versions in ModMenu: in the screenshot above, I can see that you are using Auto HUD v3.2.1+1.19.4.
Alternatively, you can look at the startup log; or at the filenames in the mods/ folder; or in your launcher somewhere.

**Comment by temginson** [comment]
Mod menu 6.2.2 other I can't find I'm using feather client

**Comment by Crendgrim** [comment]
Can you give me the whole mod list?

**Comment by temginson** [comment]
what do you mean with the whole mod list?

**Comment by Crendgrim** [comment]
The list of all of the mods in your installation. In your screenshot, it shows you have 18 mods, 7 of which are shown. I'd like to know all of the mods involved so I can try to replicate the issue.

**Comment by Crendgrim** [comment]
Since I cannot reproduce this bug, I am going to assume that your proprietary launcher is doing something weird.

In any case I have changed config libraries for version 4.0, which should as a byproduct fix whatever this was anyway.
