### ISSUE TITLE
Animation seemed to be dependent on the FPS of the game

### ISSUE THREAD

**Issue by AnstroPleuton** [Crendgrim/AutoHUD#49]
I have been noticing some really weird animations because of a server which has tons of entities. I have set the animation speed to 100 and despite that it was still very slow. Then I made a void world and unleashed the FPS limit. The animations are crazy fast even on speed of 1.

**Comment by Crendgrim** [comment]
Fixed in AutoHUD 4.0

**Comment by AnstroPleuton** [comment]
Thank you!
