### ISSUE TITLE
Hotbar item in first slot hides even when "Fade-out limit for hotbar items" is set

### ISSUE THREAD

**Issue by TheRintel** [Crendgrim/AutoHUD#50]
Regardless of the selected slot, the item in the first hotbar slot will hide with the hotbar even when set to stay on screen.
No value of the "Fade-out limit for hotbar items" setting seems to not affect the first slot.

Minecraft version: 1.19.4
Mod loader: Fabric
Mod version: 3.2.1

![Screenshot_57](https://github.com/Crendgrim/AutoHUD/assets/62038464/3d9a1f35-eaeb-47fa-b13b-4a5e1f0f6efe)
![Screenshot_55](https://github.com/Crendgrim/AutoHUD/assets/62038464/79ff5a05-276e-4964-aa7e-80c785180739)
![Screenshot_56](https://github.com/Crendgrim/AutoHUD/assets/62038464/5974e892-30d0-4a8a-b042-a9dece133e55)

**Comment by Crendgrim** [comment]
Thanks for the report! That was a weird one to track down. Fixed in AutoHUD 4.0.
