### ISSUE TITLE
Adding compat with segmented

### ISSUE THREAD

**Issue by csumpasd** [Crendgrim/AutoHUD#54]
Hi!
I'm working on a mod that makes the hotbar segmented, and I'd like to add support for your mod. The current issue is that the hotbar only gets shown when selecting an actual slot, and not when selecting a segment, which is something that doesn't yet interact with minecraft's actual inventory object. (Here's the issue: https://github.com/csumpasd/segmented/issues/6)

My question is, is there a function I can call to reveal the hotbar on demand or any other way for me to easily add support?

Thanks for the help.

**Comment by Crendgrim** [comment]
https://github.com/Crendgrim/AutoHUD/blob/1.19.4/src/main/java/mod/crend/autohud/mixin/ClientPlayerInteractionManagerMixin.java

This controls the vanilla "on slot change" trigger. You could copy that call into your mod if AutoHUD is loaded.

**Comment by csumpasd** [comment]
thanks, managed to do it!
