### ISSUE TITLE
[Feature Request] Hotbar not hiding with Create Extendo Grip in shield slot

### ISSUE THREAD

**Issue by gittibene** [Crendgrim/AutoHUD#56]
Not sure it's your "fault" but could you maybe look into that?

**Comment by Crendgrim** [comment]
I cannot reproduce this with the latest versions of Create and AutoHUD for either 1.18.2 or 1.19.2. What versions does this happen with? What is in your main hand? Are there other mods you have installed?

**Comment by gittibene** [comment]
Thank you for investigating, i'm on Fabric 1.19.2 and yes, there's a shit ton of mods installed. I'll find out which one is responsible and let you know as soon as i have some time.
