### ISSUE TITLE
Large FPS hit with specific hardware

### ISSUE THREAD

**Issue by notLily72** [Crendgrim/AutoHUD#58]
I noticed that when I have this mod enabled that it drastically lowers my fps. 

![image](https://github.com/Crendgrim/AutoHUD/assets/86197720/b8c2b1e5-d817-41e0-8ef5-84aece0c6076)
![image](https://github.com/Crendgrim/AutoHUD/assets/86197720/82191b1f-6959-4f3b-87ac-e3b343852f91)

**Comment by Crendgrim** [comment]
Oh, that is not good. Can you give me a full mod list of mods you are using?

If you have time, could you test whether you can replicate that with no mods vs. only AutoHUD installed?

**Comment by Crendgrim** [comment]
Oh wow, that is a massive decrease without any other mods present. I cannot reproduce that at all on my machine (there is no measurable difference between running AutoHUD or not). I'm assuming this is something I do that the Intel driver doesn't like at all. I'll have to get out an old Intel machine to test things, so this might take a bit to investigate.

One thing you could test: does it still have such a performance impact if you disable "Fade" mode? That is the only slightly non-standard thing I do.

**Comment by Crendgrim** [comment]
That is still a surprisingly high drop without fade mode and worth investigating. But at least it confirms that it is the extra rendering I need to do for fade mode. Thank you. It might not be possible to fully fix this, but I will try to optimise things as far as I can.

**Comment by Crendgrim** [comment]
I only have a much older Intel CPU with an integrated UHD Graphics 620. On that, I was *not* able to replicate this at all. With a scene comparable to yours, launching the game and waiting ~10 seconds for everything to stabilise, I am reaching 50fps with or without the mod (including fade mode). GPU usage is slightly higher with the mod running, so I'm afraid I'm CPU bound on this old machine. But it is nowhere close to the impact you are seeing :/

**Comment by Crendgrim** [comment]
Until I can get anything more substantial in (if that is even something I can do), version 6.0 comes with a minor performance improvement: when the hotbar is hidden, items don't get rendered at all (instead of rendered twice.. invisibly..). Won't help you much, but should do a little.

**Comment by Crendgrim** [comment]
Since I haven't heard anyone else complain about this, I'm closing this for now.

**Comment by GerG0Gadget** [comment]
Hi, I am facing the same issue (M2 MacBook Air)

However I only experience fps drop only while the hud is visible.
When it's hidden I get around 90-100 fps, but when any part of the hud is shown, it drops down to 45-47 fps.

NeoForge 1.21.4
Mods:
-Autohud
-Sodium
-Betterf3
