### ISSUE TITLE
Apple Skin hud overlay not visible

### ISSUE THREAD

**Issue by ItsMuz** [Crendgrim/AutoHUD#63]
saturation overlay and food value not visible

**Comment by Crendgrim** [comment]
What versions of Minecraft, AppleSkin and AutoHUD?

**Comment by ItsMuz** [comment]
version 1.20.1, appleskin v2.5.0 and autohud v6.1

**Comment by Crendgrim** [comment]
Hm, I cannot reproduce that. The overlay is rendered for me, and properly sticks to the food bar as well. Given you're on AutoHUD 6.1, I assume you are on Fabric? Do you have any other mods installed?

**Comment by ItsMuz** [comment]
![image](https://github.com/Crendgrim/AutoHUD/assets/112937530/a8a3a4e9-d1d6-4bd9-9f92-449fb27f60ec)
![image](https://github.com/Crendgrim/AutoHUD/assets/112937530/f7bf73a8-89bc-4163-82de-5da6bdf67bba)

**Comment by ItsMuz** [comment]
![image](https://github.com/Crendgrim/AutoHUD/assets/112937530/2479f328-6641-4bee-a1f2-5e4782e9df02)
![image](https://github.com/Crendgrim/AutoHUD/assets/112937530/48ed7e0e-1a30-47e4-804f-726fec88e082)

**Comment by Crendgrim** [comment]
I cannot reproduce this, even when using all of the mods you listed. The AppleSkin overlays are perfectly visible and move with the hunger bar.

**Comment by ItsMuz** [comment]
I found out why. It's probably because of the client I use which is LabyMod 4. I tried it on the normal version and it works as you said. I'll try to report this bug at LabyMod.
