### ISSUE TITLE
Feature Request: 'Using' policy

### ISSUE THREAD

**Issue by egshels** [Crendgrim/AutoHUD#64]
It'd be super useful to be able to have the hud reappear when using items, mining, attacking, eating, etc. It'd help keep the screen clear when you're going for a more scenic route, but would be fantastic for keeping track of everything in combat and exploration without having to swap items to tell where everything is :)

**Comment by Crendgrim** [comment]
I really like this. Some time ago, I had investigated how to keep track of "being in combat" state and struggled to find a solution. I never investigated that further. But this idea of binding it to player actions makes a lot of sense and should be easy enough to implement.

**Comment by Crendgrim** [comment]
I finally implemented this in 6.5
