### ISSUE TITLE
[Feature Request] Add a setting that makes the HUD appear when the player stands still.

### ISSUE THREAD

**Issue by RealMrUnknownymous** [Crendgrim/AutoHUD#67]
Just a box in the config that lets the HUD appear when the player stands still. When the player stands still, after a configuralble time limit, the entire HUD will reappear. When they move again, the HUD redacts like normal. It would be nice to stand still really quick, check your health and hunger, and then keep going again.

**Comment by Crendgrim** [comment]
Interesting idea. I think I like both this, and the opposite for quick screenshot possibilities.
