### ISSUE TITLE
Hotbar isnt appearing

### ISSUE THREAD

**Issue by jbugel-lol** [Crendgrim/AutoHUD#68]
the Hotbar wont load, i still can see the items in my hand and offhand
![CleanShot 2023-08-18 at 16 01 29](https://github.com/Crendgrim/AutoHUD/assets/115107409/7420c846-04c5-4171-a56b-5f12f3320e38)
## Maybe important things:
- macOS Ventura 13.4.1
- MacBook Pro M2 Pro

**Comment by Crendgrim** [comment]
The information you listed is probably not important. What I do need, however, are your versions of Minecraft, mod loader, and the mod. As well as which other mods you have installed.

**Comment by jbugel-lol** [comment]
Fabric 0.14.22
[GitHub issue mod list 1.zip](https://github.com/Crendgrim/AutoHUD/files/12380933/GitHub.issue.mod.list.1.zip) (Mod-List)
1.20.1

**Comment by Crendgrim** [comment]
That mod list is way too big to bisect for me. If you can figure out which combination of mods causes this, I would greatly appreciate it.
