### ISSUE TITLE
Experience bar component doesn't work when on a server

### ISSUE THREAD

**Issue by Crendgrim** [Crendgrim/AutoHUD#7]
With the new event based system, the experience bar doesn't get dynamic updates properly.

- it gets stuck on its initial state (no ticking!?)
- it doesn't get notified of experience changes (apparently `setExperience` isn't triggered through the packets)

**Comment by Crendgrim** [comment]
(Hopefully) fixed in 1.5.2

**Comment by znopp** [comment]
Still happening in v 1.6
 https://streamable.com/t861do

**Comment by Crendgrim** [comment]
Fixed in 1.6.1
