### ISSUE TITLE
[1.20.1] AutoHud Crash with ImmediatelyFast??

### ISSUE THREAD

**Issue by Starexify** [Crendgrim/AutoHUD#71]
Describe the bug 
AutoHud crashing because one mod, Im not sure if ImmediatelyFast or other mod is the cause but I posted a log.

ModVersion: AutoHUD 1.20.1 6.1 (Forge)

Logs:
https://pastebin.com/60ZUUKmB

**Comment by Crendgrim** [comment]
I remember ImmediatelyFast causing issues before. Try disabling the HUD batching feature.

**Comment by DarkFireNinja** [comment]
For me its crashing because of Yet Another Config Lib mod. so check if that is maybe the cause rather than ImmediatelyFast because ImmediatelyFast works fine with AutoHud for me.

**Comment by Crendgrim** [comment]
I cannot reproduce the crash, so I believe it to be YACL. Annoyingly, it *still* hasn't gotten an update to fix it from running on 1.20.1 :/ without YACL, everything seems to be working fine
