### ISSUE TITLE
view experience level more easily

### ISSUE THREAD

**Issue by QwertRvg** [Crendgrim/AutoHUD#73]
Hi, I really enjoy this mod but I have encountered an issue. I want every part to be hidden and revealed on it's own, I think it looks nicer than if everything gets revealed at once.
But I do find it annoying that with the settings that way, I have to earn XP to view my current level. I wouldn't want to always have the level viewable either.
I wanted to ask if it was possible to make the xp level, without the xp bar, connected to the hotbar. So everytime the hotbar becomes visible, so does the xp level

**Comment by Shad0wolf0** [comment]
this would be great. currently, i have the fade-out limit set to 0.10 for it. this makes it so the xp bar disappears and the xp level very faded

**Comment by Crendgrim** [comment]
Added (by default even) now in AutoHUD 6.5
