### ISSUE TITLE
Incompatibility with MineMenu, causing rendering errors

### ISSUE THREAD

**Issue by captainharrie** [Crendgrim/AutoHUD#74]
Without AutoHUD:
![image](https://github.com/Crendgrim/AutoHUD/assets/54632985/2f3a76dd-da91-4dbb-92e2-39c01c3b25de)

With AutoHUD:
![image](https://github.com/Crendgrim/AutoHUD/assets/54632985/4e68fe46-c190-4c8c-979e-25002b35266d)

AutoHUD is duplicating the MineMenu HUD two times over! It's not breaking the functionality but visually it's a mess. I'm not sure which side would need to work on fixing this, but I thought here made most sense being the one that's editing the UI and not the other way around? [MineMenu's repository is located here](https://github.com/GirafiStudios/MineMenu) if need be.

I've some other mods enabled in those screenshots as these were taken when I was identifying which particular mod that was doing this, but I have also isolated them and verified it is specifically AutoHUD on its own that's causing the issue so there isn't a third mod in the mix.

**Comment by Crendgrim** [comment]
I identified the issue. MineMenu (presumably accidentally) draws its HUD multiple times per render pass, once after each HUD component. So, as components get moved around a bit, it gets rendered in different places (all of the hotbar components moving it down, the scoreboard moving it right, and unmoved components keeping it centered as well). Fun bug!

See GirafiStudios/MineMenu#159

**Comment by Crendgrim** [comment]
Thank you for the report! Will be fixed with the next release of MineMenu :)
