### ISSUE TITLE
AutoHUD Backslot Compatibility

### ISSUE THREAD

**Issue by NotOfficeChair** [Crendgrim/AutoHUD#75]
Would love if backslot compatibility could be added if possible, at the moment if you put something into the backslot it will always render the health, hunger and hotbar.

Great work on the mod, love it and love the idea.

**Comment by Crendgrim** [comment]
Is that this mod? https://www.curseforge.com/minecraft/mc-mods/backslot

**Comment by NotOfficeChair** [comment]
Yeah that's the mod :)

**Comment by Crendgrim** [comment]
What version of Backslot, AutoHUD, Minecraft are you using? I cannot reproduce the bug you are describing (just that it doesn't hide the backslot slots).

**Comment by NotOfficeChair** [comment]
BackSlot 1.2.15 plus BackslotAddon 1.1.0

**Comment by Crendgrim** [comment]
Oh, I see what is happening. Auto HUD's default keybind to "toggle hide UI" is G, and BackSlot's default keybind to "move item to backslot" is also G. If you move an item using G, it will toggle the whole UI visibility.. hence food + health appearing. Change one of the keybinds to a different key.

**Comment by NotOfficeChair** [comment]
Haha, i'm stupid, thank you so much and thank you for your amazing mod :)

**Comment by Crendgrim** [comment]
Added proper Backslot compatibility in 6.3.1 :)
