### ISSUE TITLE
Dehydration and EnvironmentZ compat

### ISSUE THREAD

**Issue by Feliks-WR** [Crendgrim/AutoHUD#80]
Please add compat for mods:
https://modrinth.com/mod/dehydration
https://modrinth.com/mod/environmentz

**Comment by Crendgrim** [comment]
Dehydration should be supported. At least it used to be. What version of Dehydration, AutoHUD and Minecraft are you using?

**Comment by Feliks-WR** [comment]
I am using Minecraft 1.20.1, Quilt 0.21.2 / 0.22.0-beta.1 (same issue on both), QSL 7.4.0+0.90.0-1.20.1, Dehydration 1.3.4+1.20.1, AutoHUD 6.3.1+1.20.1-fabric.

The problem is that I am unable to ever see my hydration level (in survival).

**Comment by Crendgrim** [comment]
When I use those exact mods, the hydration bar appears when it gets low just as expected. And of course shows up when using the peek/toggle key binds. It follows the same configuration as the hunger bar, because I have yet to find a clean way to make modded elements configurable on their own.

**Comment by Crendgrim** [comment]
In the next version of Auto HUD, the hydration bar will always appear if it is not full and the currently held item can be consumed to fill it up (similar to food items with the hunger bar).

**Comment by Crendgrim** [comment]
I just released AutoHUD 6.3.1 with

- updated compatibility for Dehydration (currently held items + the "thirst" status effect now always reveal the bar)
- added compatibility for EnvironmentZ, which reveals its icons whenever they change between "very cold", "cold", "normal", "hot", "very hot"; and always keeps them visible on the extremes

Let me know if this behaves the way you expect it to, or if you have any feedback / wishes for changes!

**Comment by Thefatsparrow** [comment]
enviromentz not working for me im on version 2.0.8 for enviromentz and version 6.3.2 for auto hud

**Comment by Crendgrim** [comment]
Not working in what way?

**Comment by Thefatsparrow** [comment]
the hud not moving at all
