### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by oranzovypejsek** [Crendgrim/AutoHUD#81]
When starting mc mod cannot load java.lang.NoClassDefFoundError
Mod was working perfectly fine two weeks ago and then it stopped working):

![Screenshot (38)](https://github.com/Crendgrim/AutoHUD/assets/71368803/4c913eb7-c792-41c7-80ce-36b63b4d5ae6)
[crash-2023-11-25_19.47.50-fml.txt](https://github.com/Crendgrim/AutoHUD/files/13464993/crash-2023-11-25_19.47.50-fml.txt)

**Comment by Crendgrim** [comment]
You are missing ClothConfig in your installation.

**Comment by oranzovypejsek** [comment]
Thanks (:
