### ISSUE TITLE
Compatibility issue with Item Highlighter and Item Borders

### ISSUE THREAD

**Issue by Thefatsparrow** [Crendgrim/AutoHUD#82]
https://www.curseforge.com/minecraft/mc-mods/item-highlighter-fabric/files/4674914

when the hud does the animation of moving down the highlighted items dont do the animation so they stay then vanish and its quite annoying

of your trying to reproduce the issue all you do is drop an item and pick it up and it should be highlighted

![2023-12-03_13 45 06](https://github.com/Crendgrim/AutoHUD/assets/86117177/5896b184-51fe-4e92-b9ff-c2215c63971c)

not the best photo but you can see the highlighted part the star not moving with the rest of the hud i made the gui bigger so you can see the star not moving

**Comment by Crendgrim** [comment]
It appears like both Item Highlighter and Item Borders got updated to fix this for Minecraft 1.20.2.
