### ISSUE TITLE
Halo hud is hidden by auto hud.

### ISSUE THREAD

**Issue by M1hono** [Crendgrim/AutoHUD#86]
I'm currently using the newest auto hud, halo hud and dynamic crosshair. But halo hud is hidden by auto hud and unable to display normally.

**Comment by Crendgrim** [comment]
Which modloader and version of Minecraft are you using?

**Comment by M1hono** [comment]
> Which modloader and version of Minecraft are you using?

sry for late reply. I'm playing 1.20.1 forge47.1.3 and haven't tried the newest auto hud.

**Comment by Crendgrim** [comment]
AutoHUD on Forge had a bug that was fixed by the release earlier today. I believe that will also fix it hiding HaloHUD.

**Comment by Crendgrim** [comment]
I'm assuming said release fixed it. If it did not, feel free to reopen!
