### ISSUE TITLE
Slot Cycler Incompatibility  

### ISSUE THREAD

**Issue by Jouto55** [Crendgrim/AutoHUD#87]
When Auto HUD and Slot Cycler are installed, Slot Cycler's Hotbar isn't hidden.
![image](https://github.com/Crendgrim/AutoHUD/assets/148708399/8d8e1345-c9c4-4016-b58c-8bd783cfbcbf)

Version: 1.20.1
Mod loader: Fabric 0.15.3 (This bug is also on Forge, but it's the mod loader I used for the example)

**Comment by Crendgrim** [comment]
I don't understand the way Slot Cycler has laid out its code. It seems like the implementation is hidden in a bundled version of puzzleslib that isn't even released yet, let alone available on GitHub. Please ask them to add compatibility. Though considering they also don't support Raised according to their mod page, I don't know if they're interested in it.

**Comment by Crendgrim** [comment]
Compatibility has been added in AutoHUD 6.6 (6.6.1).
Let me know if it doesn't work properly in some circumstances.

**Comment by HoodBlah** [comment]
Doesnt work on 1.20.1 Forge with latest version of both mods. 

![2024-10-25_15 16 53](https://github.com/user-attachments/assets/6ceb1bbc-f267-4b66-80e4-06b469c614a1)
