### ISSUE TITLE
chat indicator stuck!

### ISSUE THREAD

**Issue by Kas295** [Crendgrim/AutoHUD#88]
![image](https://github.com/Crendgrim/AutoHUD/assets/103049347/d3a8b77a-e0fb-422b-b738-a443751a3af6)
this little thing showed up and doesn't want to go i tried everything i cant find any configure file i configure my hud via mod menu

**Comment by Kas295** [comment]
i solved the problem but god knows how.

**Comment by Crendgrim** [comment]
If you can replicate this issue, please do let me know!

**Comment by Lualttt** [comment]
can confirm i have this issue aswell

**Comment by Crendgrim** [comment]
Oh, I misunderstood. It gets stuck when it should never be rendered in the first place. I see, that makes some sense. I published a fix.

**Comment by augustsaintfreytag** [comment]
As of version 8.1, this bug has resurfaced. There may be mods posting welcome messages or debug info (e.g. DH) right after world load, making this happen reliably. Since updating AutoHUD to version 8, the chat indicator has been disabled but has not once disappeared for me, it's very annoying.

**Comment by Crendgrim** [comment]
Try version 8.1.1, I believe I have fixed that today. It's only on CurseForge so far because Modrinth had issues today.
