### ISSUE TITLE
Tweak compatibility with Raised on Forge

### ISSUE THREAD

**Issue by BookerCatch** [Crendgrim/AutoHUD#89]
It appears the compatibility with Raised 3.1.0 on Forge 1.20.1 ought to be re-calibrated. By default, having both mods installed results in the items on the hotbar being rendered a pixels higher than the hotbar itself. The issue becomes doubly apparent the higher the hotbar is raised.

![2024-01-11_09 03 03](https://github.com/Crendgrim/AutoHUD/assets/43504436/7dd2d545-720c-4a05-be75-99e05cc6ef49)

![2024-01-11_09 05 33](https://github.com/Crendgrim/AutoHUD/assets/43504436/4ae21bb9-6d73-48b1-b8ce-1af74af6fdf3)

**Comment by Crendgrim** [comment]
Oh right, I never published the fix for Forge. Will do so soon.

Related: yurisuika/Raised#75

**Comment by Crendgrim** [comment]
Pushed a new version, hope this works fine!
