### ISSUE TITLE
Appleskin and detail armor bar not hiding - Forge 1.19.2_4.3.1

### ISSUE THREAD

**Issue by Astrofishisist** [Crendgrim/AutoHUD#95]
Appleskin v2.4.2
Detail armor bar v2.6.4
Forge v43.3.5
![image](https://github.com/Crendgrim/AutoHUD/assets/147417778/6ace454e-1bab-48c9-a2de-101470038e79)
Like title, the armor bar and food saturation aren't hiding as they should be.
(Ignore the coloured dots, that's casting crystals UI and not something you can do anything about, even though it is annoying)

**Comment by Crendgrim** [comment]
AppleSkin is tracked in #66, but I won't work on 1.19.2 anymore, sorry.

**Comment by Astrofishisist** [comment]
You break my heart Crendgrim! Just kidding. Thanks for the great mod regardless!
